version: '2'
services:
    sm-app:
        image: sm
        external_links:
            - sm-postgresql:postgresql
            - sm-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/sm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    sm-postgresql:
        extends:
            file: postgresql.yml
            service: sm-postgresql
    sm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sm-elasticsearch
