package br.gov.sc.fatma.sinfat.domain.enumeration;

/**
 * The TipoLicencaEnum enumeration.
 */
public enum TipoLicencaEnum {
    NP,LAP,LAI,LAO,AUA,LAPLAI,LAILAO,LAPLAILAO,RENLAO,AMPLAP,AMPLAI,AMPLAO,AMPLAPLAI,AMPLAPLAILAO,RENAUA,RENLAI,AMPLAILAO,LAOCORRETIVA,EXPLORACAO_FLORESTAL,CONFAMBIENTAL,FAUNA,REPOSICAO
}
